database:
  url: ""
datastore:
  address: "127.0.0.1:6379"
app:
  debug: "false"
  port: 8080
allowOrigins:
  - "http://localhost:3000"
  - "https://reportify.abelab.dev"
openAI:
  key: ""
cognito:
  userPoolID: "ap-northeast-1_EAP0uZ7mB"
  clientID: ""