// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/organizations": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "自分が所属する組織のみ取得できる",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "組織リスト取得API",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.OrganizationsResponse"
                        }
                    },
                    "400": {
                        "description": "BadRequest",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/organizations/{organizationCode}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "組織取得API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "組織コード",
                        "name": "organizationCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Organization"
                        }
                    },
                    "400": {
                        "description": "BadRequest",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Organization"
                ],
                "summary": "組織更新API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "組織コード",
                        "name": "organizationCode",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "組織更新リクエスト",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.UpdateOrganizationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Organization"
                        }
                    },
                    "400": {
                        "description": "BadRequest",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/organizations/{organizationCode}/reports": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Report"
                ],
                "summary": "日報リスト取得API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "組織コード",
                        "name": "organizationCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.ReportsResponse"
                        }
                    },
                    "400": {
                        "description": "BadRequest",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Report"
                ],
                "summary": "日報作成API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "組織コード",
                        "name": "organizationCode",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "日報作成リクエスト",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.CreateReportRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/controller.CreateReportRequest"
                        }
                    },
                    "400": {
                        "description": "BadRequest",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/organizations/{organizationCode}/reports/{reportId}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Report"
                ],
                "summary": "日報取得API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "組織コード",
                        "name": "organizationCode",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "日報ID",
                        "name": "reportId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.ReportResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/organizations/{organizationCode}/users": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "組織のユーザリスト取得API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "組織コード",
                        "name": "organizationCode",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.UsersResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "メンバー招待API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "組織コード",
                        "name": "organizationCode",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "メンバー招待リクエスト",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.InviteUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.User"
                        }
                    },
                    "400": {
                        "description": "BadRequest",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/reports/{reportId}": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Report"
                ],
                "summary": "バッチ処理用の日報レビューAPI",
                "parameters": [
                    {
                        "type": "string",
                        "description": "日報ID",
                        "name": "reportId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "日報レビューリクエスト",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.ReviewReportRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/me": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "ログインユーザー取得API",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.User"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/entity.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.CreateReportRequest": {
            "type": "object",
            "properties": {
                "body": {
                    "description": "本文",
                    "type": "string"
                },
                "tasks": {
                    "description": "実施したタスクリスト",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Task"
                    }
                }
            }
        },
        "controller.InviteUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "メールアドレス",
                    "type": "string"
                }
            }
        },
        "controller.OrganizationsResponse": {
            "type": "object",
            "properties": {
                "organizations": {
                    "description": "組織リスト",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Organization"
                    }
                }
            }
        },
        "controller.ReportResponse": {
            "type": "object",
            "properties": {
                "body": {
                    "description": "本文",
                    "type": "string"
                },
                "id": {
                    "description": "日報レスポンス",
                    "type": "string"
                },
                "reviewBody": {
                    "description": "レビュー本文",
                    "type": "string"
                },
                "tasks": {
                    "description": "実施したタスクリスト",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Task"
                    }
                },
                "timestamp": {
                    "description": "作成日時",
                    "type": "string"
                },
                "userId": {
                    "description": "ユーザID",
                    "type": "string"
                },
                "userName": {
                    "description": "ユーザ名",
                    "type": "string"
                }
            }
        },
        "controller.ReportsResponse": {
            "type": "object",
            "properties": {
                "reports": {
                    "description": "日報リスト",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.ReportResponse"
                    }
                }
            }
        },
        "controller.UpdateOrganizationRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "組織コード",
                    "type": "string"
                },
                "mission": {
                    "description": "ミッション",
                    "type": "string"
                },
                "name": {
                    "description": "組織名",
                    "type": "string"
                },
                "value": {
                    "description": "バリュー",
                    "type": "string"
                },
                "vision": {
                    "description": "ビジョン",
                    "type": "string"
                }
            }
        },
        "controller.UsersResponse": {
            "type": "object",
            "properties": {
                "users": {
                    "description": "ユーザリスト",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.User"
                    }
                }
            }
        },
        "entity.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "entity.Mvv": {
            "type": "object",
            "properties": {
                "mission": {
                    "description": "ミッション",
                    "type": "string"
                },
                "value": {
                    "description": "バリュー",
                    "type": "string"
                },
                "vision": {
                    "description": "ビジョン",
                    "type": "string"
                }
            }
        },
        "entity.Organization": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "組織コード",
                    "type": "string"
                },
                "id": {
                    "description": "組織ID",
                    "type": "string"
                },
                "mvv": {
                    "$ref": "#/definitions/entity.Mvv"
                },
                "name": {
                    "description": "組織名",
                    "type": "string"
                }
            }
        },
        "entity.ReviewReportRequest": {
            "type": "object",
            "properties": {
                "reviewBody": {
                    "type": "string"
                }
            }
        },
        "entity.Task": {
            "type": "object",
            "properties": {
                "finishedAt": {
                    "description": "終了日時",
                    "type": "string"
                },
                "name": {
                    "description": "タスク名",
                    "type": "string"
                },
                "startedAt": {
                    "description": "開始日時",
                    "type": "string"
                }
            }
        },
        "entity.User": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "メールアドレス",
                    "type": "string"
                },
                "id": {
                    "description": "ユーザID",
                    "type": "string"
                },
                "name": {
                    "description": "ユーザ名",
                    "type": "string"
                },
                "organizations": {
                    "description": "所属する組織リスト",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.UserOrganization"
                    }
                }
            }
        },
        "entity.UserOrganization": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "組織ID",
                    "type": "string"
                },
                "is_admin": {
                    "description": "ロール",
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Reportify",
	Description:      "Reportify",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
